name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: docker build . -t rinha-de-backend-2023-q3
  test:
    runs-on: ubuntu-20.04
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: docker-compose up -d
    - name: Load test
      run: |
        wget https://8006059.fs1.hubspotusercontent-na1.net/hubfs/8006059/Gatling%20OSS/gatling-charts-highcharts-bundle-3.10.4-bundle.zip
        unzip gatling-charts-highcharts-bundle-3.10.4-bundle.zip -d gatling
        export GATLING_HOME=$(pwd)

        git clone --single-branch --quiet https://github.com/zanfranceschi/rinha-de-backend-2024-q1
        cd rinha-de-backend-2024-q1
        ./executar-teste-local.sh
        
        echo GATLING_OUTPUT_FOLDER=$(ls $(pwd)/load_test/user-files/results | sort | head -n 1) >> $GITHUB_ENV
      env:
        WORKSPACE: ${{ github.workspace }}/rinha-de-backend-2024-q1/load_test
    - run: echo ${{ env.GATLING_OUTPUT_FOLDER }}
    - run: |
        # replace string DESCRICAO with the commit sha in file index.html inside GATLING OUTPUT FOLDER
        sed -i "s/DESCRICAO/${{ github.sha }}/g" ${{ github.workspace }}/rinha-de-backend-2024-q1/load-test/user-files/results/${{ env.GATLING_OUTPUT_FOLDER }}/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/rinha-de-backend-2024-q1/load-test/user-files/results/${{ env.GATLING_OUTPUT_FOLDER }}
        destination_dir: ${{ env.GATLING_OUTPUT_FOLDER }}
    - run: echo "GH_REPO=$(echo ${{ github.repository }} | cut -d "/" -f 2)" >> $GITHUB_ENV
    - run: echo "[Deploying to https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }}](https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }})" >> "${GITHUB_STEP_SUMMARY}"
